import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './{components}/Nav'
import { getServerSession } from 'next-auth';
import Link from 'next/link';
import AuthProvider from './{components}/SessionProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  console.log(session)
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <AuthProvider session={session}>
          <Nav />
          {children}
        </AuthProvider>
        
      </body>
    </html>
  )
}
